# Generated by Django 4.1 on 2022-09-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(default='Basic description', max_length=255),
        ),
    ]
